version: '3.2'
services:
  graphdb:
    build:
      context: .
      dockerfile: proof/Dockerfile
    user: neo4j
    volumes:
      - type: volume
        source: data
        target: /data
      - type: volume
        source: logs
        target: /logs
      - type: volume
        source: import
        target: /import
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      app_net:
        ipv4_address: 10.0.1.18

networks:
  app_net:
    driver: bridge

    ipam:
      driver: default
      config:
      - subnet: 10.0.1.0/24

volumes:
  data:
  logs:
