version: '3.2'
services:
  proof:
    build:
      context: .
      dockerfile: proof/Dockerfile
    container_name: proof_graph
    user: neo4j
    # volumes:
      # - type: bind
      #   source: data/
      #   target: /data
    #   - type: volume
    #     source: logs/
    #     target: /logs
      # - type: bind
      #   source: import
      #   target: /csv_imports
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      app_net:
        ipv4_address: 10.0.1.18

networks:
  app_net:
    driver: bridge

    ipam:
      driver: default
      config:
      - subnet: 10.0.1.0/24

# volumes:
#   data:
#   logs:
  # import:
