FROM neo4j:latest

RUN mkdir /logs
RUN chown -R neo4j:neo4j /logs

RUN mkdir /var/lib/neo4j/csv_imports
RUN chown -R neo4j:neo4j /var/lib/neo4j/csv_imports

# VOLUME /var/lib/neo4j/data
# VOLUME /logs
# VOLUME /var/lib/neo4j/csv_imports
